### ISSUE TITLE
Cluster is not getting started

### ISSUE THREAD

**Issue by ashokpinapathula** [oneinfra/oneinfra#64] opened 2020-06-29 06:45 UTC
**System information**:

- oneinfra version
- Operating system
- Node topology
- Anything relevant to the system or set of systems where this bug is
  showing up

when iam trying to create new cluster it is not getting created and the status is showing pending

![image](https://user-images.githubusercontent.com/54942140/85981661-32034f00-ba02-11ea-8430-3496c1733e91.png)

**Comment by ereslibre** [comment] 2020-06-29 07:30
Are there any hypervisors created? You can check it with `kubectl get hypervisors -o wide`.

**Comment by ashokpinapathula** [comment] 2020-06-29 08:15
In which namespace ??

**Comment by ereslibre** [comment] 2020-06-29 08:17
Hypervisors are not namespaced, they are cluster-wide resources.

**Comment by ashokpinapathula** [comment] 2020-06-29 08:18
It's showing no resources when I fire kubectl get hypervisors

**Comment by ereslibre** [comment] 2020-06-29 08:37
That is the issue. How did you create the environment? Are you using the `demo.sh` script in https://github.com/oneinfra/oneinfra#lightning-quick-start?

**Comment by ashokpinapathula** [comment] 2020-06-29 08:47
No I have done using quick start not with the demo.sh

**Comment by ereslibre** [comment] 2020-06-29 08:49
Have you followed the step 3 in https://github.com/oneinfra/oneinfra/blob/master/docs/quick-start.md#with-kubernetes-as-a-management-cluster?

You have to either create Hypervisors manually (by installing physical or virtual machines), or if you want to just test oneinfra you can use `oi-local-hypervisor-set create --tcp | kubectl apply -f -` so some containers are resembling physical or virtual hypervisors.

**Comment by ashokpinapathula** [comment] 2020-06-29 08:57
I installed the hypervisor how and even I can see the response upon firing
kubectl get hypervisors but still iam unable to create or delete any cluster

**Comment by Aisuko** [comment] 2020-06-30 09:57
Same issue with the clusters in pending status.

<img width="1632" alt="Screen Shot 2020-06-30 at 5 57 14 PM" src="https://user-images.githubusercontent.com/8053949/86112907-25165680-bafb-11ea-946c-5f1deb5ff6ce.png">


![Screen Shot 2020-06-30 at 5 56 26 PM](https://user-images.githubusercontent.com/8053949/86112860-1760d100-bafb-11ea-8033-b746a6388b50.png)

**Comment by ereslibre** [comment] 2020-06-30 10:40
@Aisuko thank you for your feedback! It typically takes for oneinfra around one minute to provision a new cluster based on my experience.

There should be some kind of error reported by the oneinfra manager (you can also increase its verbosity in order to get more detailed errors).

In your case, new components were created for the new clusters and they were assigned hypervisors, so that looks correct. Based on the information I have right now I would increase the verbosity level of the oneinfra manager and check its logs; my impression is that the oneinfra manager might not be able to reach the CRI endpoint defined in the hypervisors, and thus, cannot create the control plane components allotted  to the different hypervisors.

**Comment by ashokpinapathula** [comment] 2020-07-01 09:42
E0701 09:39:29.576016       1 cluster_reconciler.go:72] failed to reconcile cluster "kubernetes-sample-user/demo2": kubernetes-sample-user/demo2[found one control plane ingress component, but it does not have a named host port "apiserver" yet]
I0701 09:39:48.277648       1 reconciler.go:57] pre-reconciling component "demo2-control-plane-9h5t7" with role "control-plane"
2020-07-01T09:39:48.310Z        DEBUG   controller-runtime.controller   Successfully Reconciled {"controller": "component-scheduler", "request": "kubernetes-sample-user/demo2-control-plane-9h5t7"}
I0701 09:39:48.317840       1 reconciler.go:96] reconciling component "demo2-control-plane-ingress-7hgch" with role "control-plane-ingress"
I0701 09:39:48.317881       1 control_plane_ingress.go:129] reconciling control plane ingress in component "demo2-control-plane-ingress-7hgch", present in hypervisor "test-public-hypervisor-0", belonging to cluster "demo2"
I0701 09:39:48.474955       1 reconciler.go:95] reconciling cluster "demo2"
E0701 09:39:48.474991       1 cluster_reconciler.go:72] failed to reconcile cluster "kubernetes-sample-user/demo2": kubernetes-sample-user/demo2[found one control plane ingress component, but it does not have a named host port "apiserver" yet]

found the above error what can i mistake area ??

**Comment by ereslibre** [comment] 2020-07-01 10:07
I think the issue you are experimenting @ashokpinapathula is different from the one @Aisuko is hitting.

In your case, @ashokpinapathula, please correct me if I'm wrong, the issue is that hypervisors custom resources are not registered at all (the `kubectl get hypervisors` list is empty). So, when components are created, `oneinfra` cannot schedule the different components to any hypervisors, because the hypervisor list is empty. You can check this by visiting the web UI and see if components are assigned to hypervisors, or running `kubectl get components -A`; you should see that all components are assigned to some hypervisor.

In @Aisuko's case, there is a list of hypervisors, and so, when components are created, they can be scheduled on the defined hypervisors, but the oneinfra controller manager cannot talk to the CRI endpoints in the hypervisors.

**Comment by ashokpinapathula** [comment] 2020-07-01 10:13
root@xxxxxx:~/oneinf# kubectl get hypervisors
NAME                        PUBLIC   IP ADDRESS   PORT LOW   PORT HIGH   AGE
test-private-hypervisor-0   false    172.17.0.2   30000      60000       33m
test-public-hypervisor-0    true     172.17.0.3   30000      60000       33m
root@xxxxxx:~/oneinf# kubectl get components -A
NAMESPACE                NAME                                CLUSTER   ROLE                    HYPERVISOR                  AGE
kubernetes-sample-user   demo2-control-plane-9h5t7           demo2     control-plane           test-private-hypervisor-0   32m
kubernetes-sample-user   demo2-control-plane-ingress-7hgch   demo2     control-plane-ingress   test-public-hypervisor-0    32m

iam getting responses for both hypervisors and components

**Comment by ereslibre** [comment] 2020-07-01 10:25
@ashokpinapathula could you please attach the `kubectl get components -o yaml`, `kubectl get clusters -o yaml` and the `kubectl get hypervisors -o yaml` outputs as files here as well?

**Comment by ashokpinapathula** [comment] 2020-07-01 10:44
[clusters.txt](https://github.com/oneinfra/oneinfra/files/4857325/clusters.txt)
[components.txt](https://github.com/oneinfra/oneinfra/files/4857327/components.txt)
[hypervisors.txt](https://github.com/oneinfra/oneinfra/files/4857328/hypervisors.txt)

**Comment by ereslibre** [comment] 2020-07-01 10:57
@ashokpinapathula ouch I'm sorry, I meant `kubectl get components -o yaml -A` and `kubectl get clusters -o yaml -A`, so we list all components and clusters from all namespaces. Sorry for that.

**Comment by ashokpinapathula** [comment] 2020-07-01 15:03
[clusters.txt](https://github.com/oneinfra/oneinfra/files/4858640/clusters.txt)
[components.txt](https://github.com/oneinfra/oneinfra/files/4858641/components.txt)
[hypervisors.txt](https://github.com/oneinfra/oneinfra/files/4858642/hypervisors.txt)

These are the yamls with -A

**Comment by ereslibre** [comment] 2020-07-02 09:03
@ashokpinapathula the `clusters.txt` file is incomplete. I can see however that on `components.txt` all of them have `apiserver`, `etcd-client` and `etcd-peer` in the private `allocatedHostPorts` and `apiserver` in the public `allocatedHostPorts`, what signals that the error message you posted before should have been a transient message that was printed when the `apiserver` host port was not allocated yet, but not the reason for failure.

**Comment by ereslibre** [comment] 2020-07-16 10:38
Closing this issue after some time without feedback, please, feel free to reopen.

**Closed by ereslibre** 2020-07-16 10:38 UTC
Labels: kind/bug, triaging/more-evidence-needed, triaging/untriaged
